env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  -
    binary: skeleton
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  -
    builds:
      - skeleton
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64

nfpms:
  -
    vendor: kowalski
    homepage: "https://ko.wal.ski/"
    maintainer: "Kristof Kowalski <k@ko.wal.ski>"
    description: "Skeleton App, a bare bones Go cli app"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

brews:
  - goarm: 6
    tap:
      owner: kowalski
      name: homebrew-tap
    commit_author:
      name: "Kristof Kowalski"
      email: "k@ko.wal.ski"
    homepage: "https://ko.wal.ski/"
    description: "Skeleton App, a bare bones Go cli app"
    # skip_upload: true

# snapcrafts:
#   -
#     name: skeleton
#     publish: true
#     summary: Skeleton App, a bare bones Go cli app
#     description: |
#       Skeleton App, a bare bones Go cli app.

#     grade: stable
#     confinement: strict
#     license: MIT
#     base: core20

#     apps:
#       skeleton:
#         plugs: ["home", "network"]

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
