name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18
      # - name: Set up Snapcraft
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
      #     mkdir -p $HOME/.cache/snapcraft/download
      #     mkdir -p $HOME/.cache/snapcraft/stage-packages
      # - name: Login Snapcraft
      #   env:
      #     SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
      #   if: env.SNAPCRAFT_LOGIN != null
      #   run: snapcraft login --with <(echo "$SNAPCRAFT_LOGIN")
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --skip-sign --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: skeleton
          path: dist/*
